/**
 * 
 */
package com.breakoutms.lfs.server.products.model;

/**
 * @author Ntholi Nkhatho
 *
 */
public enum ProductType { //TODO: WHEN IMPORTING ANY VALUE ASSOCIATED WITH THIS TYPE FROM THE OLD DATABASE
	//TODO: REMEMEBER THAT VALUES WHERE SAVED AS INTEGER AND THOSE INTEGER VALUES MAY NOT MAPP WELL WITH
	//TODO: THIS ENUM

	COFFIN_CASKET,
	CREMATION,
	ERECTION,
	LETTERS,
	MORTUARY,
	REFRIGERATION,
	PROGRAMS,
	SERVICES,
	TOMBSTONE,
	TRANSPORT,
	WREATHS,
	OTHER;
}

